#!/usr/bin/env python3
"""EWF fonts-only 生成并同步到 generated/fonts（禁止手改 .c 位图）。"""
from __future__ import annotations
import argparse, hashlib, json, re, shutil, subprocess, sys, tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]  # Embedded/
SL = ROOT / "lvgl-design/squareline_studio"
FONT_DIR = SL / "assets/Fonts"
FONT_CONV = Path("/Applications/SquareLine_Studio.app/Contents/MacOS/lvgl/lv_font_conv-osx")


def symbols() -> str:
    canon = ROOT.parent / "docs/contracts/canonical/heart-sutra.txt"
    text = canon.read_text(encoding="utf-8")
    han = set(re.findall(r"[\u4e00-\u9fff]", text))
    ui = set("木鱼经文统计设置同步中待同步同步失败已同步电量低电故障未校时今日累计心经进度音量亮度熄屏立即同步关闭开启待校时第次诵读敲击本次已完成进行中字屏幕自动版本高低秒本轮完成从头开始退出")
    punct = set("，。：%/-+·")
    ascii_dyn = set(chr(c) for c in range(0x20, 0x7F))
    return "".join(sorted(han | ui | punct | ascii_dyn))


def instantiate_serif(vf: Path, weight: int, out: Path) -> None:
    subprocess.run(
        ["fonttools", "varLib.instancer", str(vf), f"wght={weight}", "-o", str(out)],
        check=True,
        capture_output=True,
        text=True,
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--fonts-only", action="store_true")
    ap.add_argument("--sync-generated-fonts", type=Path, required=True)
    ap.add_argument("--serif-source", type=Path, default=Path("/tmp/NotoSerifSC-VF.ttf"))
    ap.add_argument("--font-conv", type=Path, default=FONT_CONV)
    args = ap.parse_args()
    if not args.fonts_only:
        print("本工具仅支持 --fonts-only", file=sys.stderr)
        return 2
    if not args.font_conv.exists():
        print(f"缺少 lv_font_conv: {args.font_conv}", file=sys.stderr)
        return 1
    syms = symbols()
    serif_vf = args.serif_source if args.serif_source.exists() else None

    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        serif_fonts: dict[int, Path] = {}
        if serif_vf is not None:
            for weight in (400, 500, 700):
                out = tmp_path / f"NotoSerifSC-{weight}.ttf"
                instantiate_serif(serif_vf, weight, out)
                serif_fonts[weight] = out
                shutil.copy2(out, FONT_DIR / out.name)

        outs = [
            ("ui_font_ns600_16", FONT_DIR / "NotoSansSC-600.ttf", 16, None),
            ("ui_font_ns700_22", FONT_DIR / "NotoSansSC-700.ttf", 22, None),
            ("ui_font_serif700_28", serif_fonts.get(700, FONT_DIR / "NotoSerifSC-700.ttf"), 28, 700),
            ("ui_font_serif700_52", serif_fonts.get(700, FONT_DIR / "NotoSerifSC-700.ttf"), 52, 700),
            ("ui_font_serif500_26", serif_fonts.get(500, FONT_DIR / "NotoSerifSC-500.ttf"), 26, 500),
            ("ui_font_serif400_26", serif_fonts.get(400, FONT_DIR / "NotoSerifSC-400.ttf"), 26, 400),
        ]
        for name, src, size, weight in outs:
            if weight is not None and not src.exists():
                print(
                    f"缺少 Serif 源字体: {src}（禁止用 Sans 冒充经文字形）",
                    file=sys.stderr,
                )
                return 1
            if "Sans" in src.name and name.startswith("ui_font_serif"):
                print(
                    f"Serif 档回退到 Sans 被拒绝: {name} <- {src.name}",
                    file=sys.stderr,
                )
                return 1
        args.sync_generated_fonts.mkdir(parents=True, exist_ok=True)
        for name, src, size, weight in outs:
            out = args.sync_generated_fonts / f"{name}.c"
            cmd = [
                str(args.font_conv),
                "--font",
                str(src),
                "--size",
                str(size),
                "--format",
                "lvgl",
                "--bpp",
                "4",
                "--no-compress",
                "--lv-include",
                "lvgl.h",
                "-o",
                str(out),
                "--symbols",
                syms,
            ]
            print("RUN", name, "weight", weight)
            r = subprocess.run(cmd, capture_output=True, text=True)
            if r.returncode != 0:
                print(r.stderr, file=sys.stderr)
                return r.returncode
            shutil.copy2(out, FONT_DIR / out.name)
            (FONT_DIR / f"{name}.fcfg").write_text(
                json.dumps(
                    {
                        "name": name,
                        "size": size,
                        "bpp": 4,
                        "source": src.name,
                        "weight": weight,
                        "symbols_sha1": hashlib.sha1(syms.encode()).hexdigest(),
                        "note": "Generated by Story 3.2 fonts-only pipeline; do not hand-edit .c",
                    },
                    ensure_ascii=False,
                    indent=2,
                )
                + "\n",
                encoding="utf-8",
            )
    print("fonts-only sync OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
