idf_component_register(
    SRCS
        "i2c_manager/i2c_manager.c"
        "event_bus/event_bus.c"
        "config_service/config_service.c"
    INCLUDE_DIRS
        "i2c_manager"
        "event_bus"
        "config_service"
    REQUIRES
        BSP
        esp_driver_i2c
        esp_driver_uart
        esp_hw_support
        freertos
        nvs_flash
)
